### ISSUE TITLE
Build a dedicated interface for visual regression tests

### ISSUE THREAD

**Issue by adela-istrate-hs** [uberVU/mocha-mugshot-reporter#21]
## Idea
```gherkin
As a user
I want to have an interactive interface
So that I can see why my visual tests fail
```

## What we have now

![screen shot 2016-08-01 at 5 22 29 pm](https://cloud.githubusercontent.com/assets/20299984/17297046/a0532446-580c-11e6-86dd-2bc7e3c07471.png)

## What we need

An interface dedicated to visual regression tests, more than what other existing mocha reporters have to offer.

## Solution

Make it more user friendly.
Add some style.
View images in more interactive way (e.g. [like in GitHub](https://github.com/cameronmcefee/Image-Diff-View-Modes/commit/8e95f70c9c47168305970e91021072673d7cdad8)).

### Use Cases

Given I run the visual tests
When I open the visual report
Then I see a list of my tests description (passed/failed)
and the total number of tests (passed/failed)
and the total time it took to run the tests

Given I am in the visual report home page
When I click the 'passed' button
Then I see only the passed tests

Given I am in the visual report home page
When I click the 'failed' button
Then I see only the failed tests

Given I am in the visual report 'passed' or 'failed' page
When I click the 'all' button
Then I see all the tests (passed/failed)

Given I am in the visual report
When I click a passed test description
Then I see the baseline

Given I am in the visual report
When I click a failed test description
Then I see the visual regression (the baseline and the new screenshot side by side)

Given I see the visual regression
When I am not sure what is different
Then I can choose between this views: 'default' (mugshot diff image), 'swipe', 'fade'

### Tools

[React-Image-Diff](https://github.com/cezary/react-image-diff)

### Tasks

- [x] Think about a design
- [x] Integrate the [React-Image-Diff](https://github.com/cezary/react-image-diff) package
- [x] Take input from user (e.g. [React-Image-Diff Demo](http://cezarywojtkowski.com/react-image-diff/))
- [x] Add some style
- [x] Display error message for failed tests

**Comment by adela-istrate-hs** [comment]
@valentin-radulescu-hs @flavius-tirnacop-hs @andrei-picus-hs @catalin-miron-hs
Do you have any other ideas or suggestions?

**Comment by flavius-tirnacop-hs** [comment]
LGTM

**Comment by adela-istrate-hs** [comment]
@valentin-radulescu-hs @flavius-tirnacop-hs @andrei-picus-hs Can I merge this into master and publish this package to npm?

**Comment by valentin-radulescu-hs** [comment]
@adela-istrate-hs Go for it!

**Comment by flavius-tirnacop-hs** [comment]
👌
