### ISSUE TITLE
Bundle Bootstrap

### ISSUE THREAD

**Issue by andrei-picus-hs** [uberVU/mocha-mugshot-reporter#36]
## Need

```gherkin
As a developer
I don't want my code to depend on implementation details
So that I can reuse it anywhere.
```

The above is not satisfied currently and we're depending on the location of Bootstrap inside the `node_modules` hierarchy.

## Deliverables

- [ ] Bootstrap is bundled in the report bundle.

## Solution

Remove `bootstrap.min.css` from [`index.html`](https://github.com/uberVU/mocha-mugshot-reporter/blob/f254e620fff034f44083f0b4911bfc24ab6f6a2f/statics/index.html#L7) and instead `import` it in [`entry.jsx`](https://github.com/uberVU/mocha-mugshot-reporter/blob/f254e620fff034f44083f0b4911bfc24ab6f6a2f/ui/entry.jsx).

#### TODO

- [x] import the Bootstrap CSS in the bundle entry point
- [x] remove Bootstrap as a production dependency and move it to dev dependencies
